package com.lovers.java.mapper;

import com.lovers.java.domain.SysFile;
import com.lovers.java.domain.SysFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    long countByExample(SysFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int deleteByExample(SysFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int deleteByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int insert(SysFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int insertSelective(SysFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    List<SysFile> selectByExample(SysFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    SysFile selectByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysFile record, @Param("example") SysFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByExample(@Param("record") SysFile record, @Param("example") SysFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByPrimaryKeySelective(SysFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByPrimaryKey(SysFile record);
}