package com.lovers.java.mapper;

import com.lovers.java.domain.UserFriend;
import com.lovers.java.domain.UserFriendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    long countByExample(UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int deleteByExample(UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int deleteByPrimaryKey(Integer userFriendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int insert(UserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int insertSelective(UserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    List<UserFriend> selectByExample(UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    UserFriend selectByPrimaryKey(Integer userFriendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserFriend record, @Param("example") UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByExample(@Param("record") UserFriend record, @Param("example") UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByPrimaryKeySelective(UserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByPrimaryKey(UserFriend record);
}