package com.lovers.java.mapper;

import com.lovers.java.domain.UserPhotoAlbum;
import com.lovers.java.domain.UserPhotoAlbumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPhotoAlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo_album
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    long countByExample(UserPhotoAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo_album
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int deleteByExample(UserPhotoAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo_album
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int deleteByPrimaryKey(Integer albumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo_album
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int insert(UserPhotoAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo_album
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int insertSelective(UserPhotoAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo_album
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    List<UserPhotoAlbum> selectByExample(UserPhotoAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo_album
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    UserPhotoAlbum selectByPrimaryKey(Integer albumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo_album
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserPhotoAlbum record, @Param("example") UserPhotoAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo_album
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByExample(@Param("record") UserPhotoAlbum record, @Param("example") UserPhotoAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo_album
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByPrimaryKeySelective(UserPhotoAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo_album
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByPrimaryKey(UserPhotoAlbum record);
}