package com.lovers.java.mapper;

import com.lovers.java.domain.UserMoodComment;
import com.lovers.java.domain.UserMoodCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;


public interface UserMoodCommentMapper  {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_comment
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    long countByExample(UserMoodCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_comment
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int deleteByExample(UserMoodCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_comment
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_comment
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int insert(UserMoodComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_comment
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int insertSelective(UserMoodComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_comment
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    List<UserMoodComment> selectByExample(UserMoodCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_comment
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    UserMoodComment selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_comment
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserMoodComment record, @Param("example") UserMoodCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_comment
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByExample(@Param("record") UserMoodComment record, @Param("example") UserMoodCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_comment
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByPrimaryKeySelective(UserMoodComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_comment
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByPrimaryKey(UserMoodComment record);
}