package com.lovers.java.mapper;

import com.lovers.java.domain.WorkflowNode;
import com.lovers.java.domain.WorkflowNodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;


public interface WorkflowNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_node
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    long countByExample(WorkflowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_node
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int deleteByExample(WorkflowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_node
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int deleteByPrimaryKey(Integer nodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_node
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int insert(WorkflowNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_node
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int insertSelective(WorkflowNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_node
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    List<WorkflowNode> selectByExample(WorkflowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_node
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    WorkflowNode selectByPrimaryKey(Integer nodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_node
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") WorkflowNode record, @Param("example") WorkflowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_node
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByExample(@Param("record") WorkflowNode record, @Param("example") WorkflowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_node
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByPrimaryKeySelective(WorkflowNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_node
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    int updateByPrimaryKey(WorkflowNode record);
}