package com.lovers.java.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LoversActionWorkflowExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lovers_action_workflow
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lovers_action_workflow
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lovers_action_workflow
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_action_workflow
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public LoversActionWorkflowExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_action_workflow
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_action_workflow
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_action_workflow
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_action_workflow
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_action_workflow
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_action_workflow
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_action_workflow
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_action_workflow
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_action_workflow
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_action_workflow
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lovers_action_workflow
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andActionIdIsNull() {
            addCriterion("action_id is null");
            return (Criteria) this;
        }

        public Criteria andActionIdIsNotNull() {
            addCriterion("action_id is not null");
            return (Criteria) this;
        }

        public Criteria andActionIdEqualTo(Integer value) {
            addCriterion("action_id =", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdNotEqualTo(Integer value) {
            addCriterion("action_id <>", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdGreaterThan(Integer value) {
            addCriterion("action_id >", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("action_id >=", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdLessThan(Integer value) {
            addCriterion("action_id <", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdLessThanOrEqualTo(Integer value) {
            addCriterion("action_id <=", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdIn(List<Integer> values) {
            addCriterion("action_id in", values, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdNotIn(List<Integer> values) {
            addCriterion("action_id not in", values, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdBetween(Integer value1, Integer value2) {
            addCriterion("action_id between", value1, value2, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("action_id not between", value1, value2, "actionId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdIsNull() {
            addCriterion("originator_id is null");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdIsNotNull() {
            addCriterion("originator_id is not null");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdEqualTo(Integer value) {
            addCriterion("originator_id =", value, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdNotEqualTo(Integer value) {
            addCriterion("originator_id <>", value, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdGreaterThan(Integer value) {
            addCriterion("originator_id >", value, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("originator_id >=", value, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdLessThan(Integer value) {
            addCriterion("originator_id <", value, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdLessThanOrEqualTo(Integer value) {
            addCriterion("originator_id <=", value, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdIn(List<Integer> values) {
            addCriterion("originator_id in", values, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdNotIn(List<Integer> values) {
            addCriterion("originator_id not in", values, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdBetween(Integer value1, Integer value2) {
            addCriterion("originator_id between", value1, value2, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("originator_id not between", value1, value2, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorNameIsNull() {
            addCriterion("originator_name is null");
            return (Criteria) this;
        }

        public Criteria andOriginatorNameIsNotNull() {
            addCriterion("originator_name is not null");
            return (Criteria) this;
        }

        public Criteria andOriginatorNameEqualTo(String value) {
            addCriterion("originator_name =", value, "originatorName");
            return (Criteria) this;
        }

        public Criteria andOriginatorNameNotEqualTo(String value) {
            addCriterion("originator_name <>", value, "originatorName");
            return (Criteria) this;
        }

        public Criteria andOriginatorNameGreaterThan(String value) {
            addCriterion("originator_name >", value, "originatorName");
            return (Criteria) this;
        }

        public Criteria andOriginatorNameGreaterThanOrEqualTo(String value) {
            addCriterion("originator_name >=", value, "originatorName");
            return (Criteria) this;
        }

        public Criteria andOriginatorNameLessThan(String value) {
            addCriterion("originator_name <", value, "originatorName");
            return (Criteria) this;
        }

        public Criteria andOriginatorNameLessThanOrEqualTo(String value) {
            addCriterion("originator_name <=", value, "originatorName");
            return (Criteria) this;
        }

        public Criteria andOriginatorNameLike(String value) {
            addCriterion("originator_name like", value, "originatorName");
            return (Criteria) this;
        }

        public Criteria andOriginatorNameNotLike(String value) {
            addCriterion("originator_name not like", value, "originatorName");
            return (Criteria) this;
        }

        public Criteria andOriginatorNameIn(List<String> values) {
            addCriterion("originator_name in", values, "originatorName");
            return (Criteria) this;
        }

        public Criteria andOriginatorNameNotIn(List<String> values) {
            addCriterion("originator_name not in", values, "originatorName");
            return (Criteria) this;
        }

        public Criteria andOriginatorNameBetween(String value1, String value2) {
            addCriterion("originator_name between", value1, value2, "originatorName");
            return (Criteria) this;
        }

        public Criteria andOriginatorNameNotBetween(String value1, String value2) {
            addCriterion("originator_name not between", value1, value2, "originatorName");
            return (Criteria) this;
        }

        public Criteria andActionStartTimeIsNull() {
            addCriterion("action_start_time is null");
            return (Criteria) this;
        }

        public Criteria andActionStartTimeIsNotNull() {
            addCriterion("action_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andActionStartTimeEqualTo(Date value) {
            addCriterion("action_start_time =", value, "actionStartTime");
            return (Criteria) this;
        }

        public Criteria andActionStartTimeNotEqualTo(Date value) {
            addCriterion("action_start_time <>", value, "actionStartTime");
            return (Criteria) this;
        }

        public Criteria andActionStartTimeGreaterThan(Date value) {
            addCriterion("action_start_time >", value, "actionStartTime");
            return (Criteria) this;
        }

        public Criteria andActionStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("action_start_time >=", value, "actionStartTime");
            return (Criteria) this;
        }

        public Criteria andActionStartTimeLessThan(Date value) {
            addCriterion("action_start_time <", value, "actionStartTime");
            return (Criteria) this;
        }

        public Criteria andActionStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("action_start_time <=", value, "actionStartTime");
            return (Criteria) this;
        }

        public Criteria andActionStartTimeIn(List<Date> values) {
            addCriterion("action_start_time in", values, "actionStartTime");
            return (Criteria) this;
        }

        public Criteria andActionStartTimeNotIn(List<Date> values) {
            addCriterion("action_start_time not in", values, "actionStartTime");
            return (Criteria) this;
        }

        public Criteria andActionStartTimeBetween(Date value1, Date value2) {
            addCriterion("action_start_time between", value1, value2, "actionStartTime");
            return (Criteria) this;
        }

        public Criteria andActionStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("action_start_time not between", value1, value2, "actionStartTime");
            return (Criteria) this;
        }

        public Criteria andActionEndTimeIsNull() {
            addCriterion("action_end_time is null");
            return (Criteria) this;
        }

        public Criteria andActionEndTimeIsNotNull() {
            addCriterion("action_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andActionEndTimeEqualTo(Date value) {
            addCriterion("action_end_time =", value, "actionEndTime");
            return (Criteria) this;
        }

        public Criteria andActionEndTimeNotEqualTo(Date value) {
            addCriterion("action_end_time <>", value, "actionEndTime");
            return (Criteria) this;
        }

        public Criteria andActionEndTimeGreaterThan(Date value) {
            addCriterion("action_end_time >", value, "actionEndTime");
            return (Criteria) this;
        }

        public Criteria andActionEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("action_end_time >=", value, "actionEndTime");
            return (Criteria) this;
        }

        public Criteria andActionEndTimeLessThan(Date value) {
            addCriterion("action_end_time <", value, "actionEndTime");
            return (Criteria) this;
        }

        public Criteria andActionEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("action_end_time <=", value, "actionEndTime");
            return (Criteria) this;
        }

        public Criteria andActionEndTimeIn(List<Date> values) {
            addCriterion("action_end_time in", values, "actionEndTime");
            return (Criteria) this;
        }

        public Criteria andActionEndTimeNotIn(List<Date> values) {
            addCriterion("action_end_time not in", values, "actionEndTime");
            return (Criteria) this;
        }

        public Criteria andActionEndTimeBetween(Date value1, Date value2) {
            addCriterion("action_end_time between", value1, value2, "actionEndTime");
            return (Criteria) this;
        }

        public Criteria andActionEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("action_end_time not between", value1, value2, "actionEndTime");
            return (Criteria) this;
        }

        public Criteria andActualStartTimeIsNull() {
            addCriterion("actual_start_time is null");
            return (Criteria) this;
        }

        public Criteria andActualStartTimeIsNotNull() {
            addCriterion("actual_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andActualStartTimeEqualTo(Date value) {
            addCriterion("actual_start_time =", value, "actualStartTime");
            return (Criteria) this;
        }

        public Criteria andActualStartTimeNotEqualTo(Date value) {
            addCriterion("actual_start_time <>", value, "actualStartTime");
            return (Criteria) this;
        }

        public Criteria andActualStartTimeGreaterThan(Date value) {
            addCriterion("actual_start_time >", value, "actualStartTime");
            return (Criteria) this;
        }

        public Criteria andActualStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("actual_start_time >=", value, "actualStartTime");
            return (Criteria) this;
        }

        public Criteria andActualStartTimeLessThan(Date value) {
            addCriterion("actual_start_time <", value, "actualStartTime");
            return (Criteria) this;
        }

        public Criteria andActualStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("actual_start_time <=", value, "actualStartTime");
            return (Criteria) this;
        }

        public Criteria andActualStartTimeIn(List<Date> values) {
            addCriterion("actual_start_time in", values, "actualStartTime");
            return (Criteria) this;
        }

        public Criteria andActualStartTimeNotIn(List<Date> values) {
            addCriterion("actual_start_time not in", values, "actualStartTime");
            return (Criteria) this;
        }

        public Criteria andActualStartTimeBetween(Date value1, Date value2) {
            addCriterion("actual_start_time between", value1, value2, "actualStartTime");
            return (Criteria) this;
        }

        public Criteria andActualStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("actual_start_time not between", value1, value2, "actualStartTime");
            return (Criteria) this;
        }

        public Criteria andActualEndTimeIsNull() {
            addCriterion("actual_end_time is null");
            return (Criteria) this;
        }

        public Criteria andActualEndTimeIsNotNull() {
            addCriterion("actual_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andActualEndTimeEqualTo(Date value) {
            addCriterion("actual_end_time =", value, "actualEndTime");
            return (Criteria) this;
        }

        public Criteria andActualEndTimeNotEqualTo(Date value) {
            addCriterion("actual_end_time <>", value, "actualEndTime");
            return (Criteria) this;
        }

        public Criteria andActualEndTimeGreaterThan(Date value) {
            addCriterion("actual_end_time >", value, "actualEndTime");
            return (Criteria) this;
        }

        public Criteria andActualEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("actual_end_time >=", value, "actualEndTime");
            return (Criteria) this;
        }

        public Criteria andActualEndTimeLessThan(Date value) {
            addCriterion("actual_end_time <", value, "actualEndTime");
            return (Criteria) this;
        }

        public Criteria andActualEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("actual_end_time <=", value, "actualEndTime");
            return (Criteria) this;
        }

        public Criteria andActualEndTimeIn(List<Date> values) {
            addCriterion("actual_end_time in", values, "actualEndTime");
            return (Criteria) this;
        }

        public Criteria andActualEndTimeNotIn(List<Date> values) {
            addCriterion("actual_end_time not in", values, "actualEndTime");
            return (Criteria) this;
        }

        public Criteria andActualEndTimeBetween(Date value1, Date value2) {
            addCriterion("actual_end_time between", value1, value2, "actualEndTime");
            return (Criteria) this;
        }

        public Criteria andActualEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("actual_end_time not between", value1, value2, "actualEndTime");
            return (Criteria) this;
        }

        public Criteria andActionSiteIsNull() {
            addCriterion("action_site is null");
            return (Criteria) this;
        }

        public Criteria andActionSiteIsNotNull() {
            addCriterion("action_site is not null");
            return (Criteria) this;
        }

        public Criteria andActionSiteEqualTo(String value) {
            addCriterion("action_site =", value, "actionSite");
            return (Criteria) this;
        }

        public Criteria andActionSiteNotEqualTo(String value) {
            addCriterion("action_site <>", value, "actionSite");
            return (Criteria) this;
        }

        public Criteria andActionSiteGreaterThan(String value) {
            addCriterion("action_site >", value, "actionSite");
            return (Criteria) this;
        }

        public Criteria andActionSiteGreaterThanOrEqualTo(String value) {
            addCriterion("action_site >=", value, "actionSite");
            return (Criteria) this;
        }

        public Criteria andActionSiteLessThan(String value) {
            addCriterion("action_site <", value, "actionSite");
            return (Criteria) this;
        }

        public Criteria andActionSiteLessThanOrEqualTo(String value) {
            addCriterion("action_site <=", value, "actionSite");
            return (Criteria) this;
        }

        public Criteria andActionSiteLike(String value) {
            addCriterion("action_site like", value, "actionSite");
            return (Criteria) this;
        }

        public Criteria andActionSiteNotLike(String value) {
            addCriterion("action_site not like", value, "actionSite");
            return (Criteria) this;
        }

        public Criteria andActionSiteIn(List<String> values) {
            addCriterion("action_site in", values, "actionSite");
            return (Criteria) this;
        }

        public Criteria andActionSiteNotIn(List<String> values) {
            addCriterion("action_site not in", values, "actionSite");
            return (Criteria) this;
        }

        public Criteria andActionSiteBetween(String value1, String value2) {
            addCriterion("action_site between", value1, value2, "actionSite");
            return (Criteria) this;
        }

        public Criteria andActionSiteNotBetween(String value1, String value2) {
            addCriterion("action_site not between", value1, value2, "actionSite");
            return (Criteria) this;
        }

        public Criteria andActualSiteIsNull() {
            addCriterion("actual_site is null");
            return (Criteria) this;
        }

        public Criteria andActualSiteIsNotNull() {
            addCriterion("actual_site is not null");
            return (Criteria) this;
        }

        public Criteria andActualSiteEqualTo(String value) {
            addCriterion("actual_site =", value, "actualSite");
            return (Criteria) this;
        }

        public Criteria andActualSiteNotEqualTo(String value) {
            addCriterion("actual_site <>", value, "actualSite");
            return (Criteria) this;
        }

        public Criteria andActualSiteGreaterThan(String value) {
            addCriterion("actual_site >", value, "actualSite");
            return (Criteria) this;
        }

        public Criteria andActualSiteGreaterThanOrEqualTo(String value) {
            addCriterion("actual_site >=", value, "actualSite");
            return (Criteria) this;
        }

        public Criteria andActualSiteLessThan(String value) {
            addCriterion("actual_site <", value, "actualSite");
            return (Criteria) this;
        }

        public Criteria andActualSiteLessThanOrEqualTo(String value) {
            addCriterion("actual_site <=", value, "actualSite");
            return (Criteria) this;
        }

        public Criteria andActualSiteLike(String value) {
            addCriterion("actual_site like", value, "actualSite");
            return (Criteria) this;
        }

        public Criteria andActualSiteNotLike(String value) {
            addCriterion("actual_site not like", value, "actualSite");
            return (Criteria) this;
        }

        public Criteria andActualSiteIn(List<String> values) {
            addCriterion("actual_site in", values, "actualSite");
            return (Criteria) this;
        }

        public Criteria andActualSiteNotIn(List<String> values) {
            addCriterion("actual_site not in", values, "actualSite");
            return (Criteria) this;
        }

        public Criteria andActualSiteBetween(String value1, String value2) {
            addCriterion("actual_site between", value1, value2, "actualSite");
            return (Criteria) this;
        }

        public Criteria andActualSiteNotBetween(String value1, String value2) {
            addCriterion("actual_site not between", value1, value2, "actualSite");
            return (Criteria) this;
        }

        public Criteria andActionContentIsNull() {
            addCriterion("action_content is null");
            return (Criteria) this;
        }

        public Criteria andActionContentIsNotNull() {
            addCriterion("action_content is not null");
            return (Criteria) this;
        }

        public Criteria andActionContentEqualTo(String value) {
            addCriterion("action_content =", value, "actionContent");
            return (Criteria) this;
        }

        public Criteria andActionContentNotEqualTo(String value) {
            addCriterion("action_content <>", value, "actionContent");
            return (Criteria) this;
        }

        public Criteria andActionContentGreaterThan(String value) {
            addCriterion("action_content >", value, "actionContent");
            return (Criteria) this;
        }

        public Criteria andActionContentGreaterThanOrEqualTo(String value) {
            addCriterion("action_content >=", value, "actionContent");
            return (Criteria) this;
        }

        public Criteria andActionContentLessThan(String value) {
            addCriterion("action_content <", value, "actionContent");
            return (Criteria) this;
        }

        public Criteria andActionContentLessThanOrEqualTo(String value) {
            addCriterion("action_content <=", value, "actionContent");
            return (Criteria) this;
        }

        public Criteria andActionContentLike(String value) {
            addCriterion("action_content like", value, "actionContent");
            return (Criteria) this;
        }

        public Criteria andActionContentNotLike(String value) {
            addCriterion("action_content not like", value, "actionContent");
            return (Criteria) this;
        }

        public Criteria andActionContentIn(List<String> values) {
            addCriterion("action_content in", values, "actionContent");
            return (Criteria) this;
        }

        public Criteria andActionContentNotIn(List<String> values) {
            addCriterion("action_content not in", values, "actionContent");
            return (Criteria) this;
        }

        public Criteria andActionContentBetween(String value1, String value2) {
            addCriterion("action_content between", value1, value2, "actionContent");
            return (Criteria) this;
        }

        public Criteria andActionContentNotBetween(String value1, String value2) {
            addCriterion("action_content not between", value1, value2, "actionContent");
            return (Criteria) this;
        }

        public Criteria andActualContentIsNull() {
            addCriterion("actual_content is null");
            return (Criteria) this;
        }

        public Criteria andActualContentIsNotNull() {
            addCriterion("actual_content is not null");
            return (Criteria) this;
        }

        public Criteria andActualContentEqualTo(String value) {
            addCriterion("actual_content =", value, "actualContent");
            return (Criteria) this;
        }

        public Criteria andActualContentNotEqualTo(String value) {
            addCriterion("actual_content <>", value, "actualContent");
            return (Criteria) this;
        }

        public Criteria andActualContentGreaterThan(String value) {
            addCriterion("actual_content >", value, "actualContent");
            return (Criteria) this;
        }

        public Criteria andActualContentGreaterThanOrEqualTo(String value) {
            addCriterion("actual_content >=", value, "actualContent");
            return (Criteria) this;
        }

        public Criteria andActualContentLessThan(String value) {
            addCriterion("actual_content <", value, "actualContent");
            return (Criteria) this;
        }

        public Criteria andActualContentLessThanOrEqualTo(String value) {
            addCriterion("actual_content <=", value, "actualContent");
            return (Criteria) this;
        }

        public Criteria andActualContentLike(String value) {
            addCriterion("actual_content like", value, "actualContent");
            return (Criteria) this;
        }

        public Criteria andActualContentNotLike(String value) {
            addCriterion("actual_content not like", value, "actualContent");
            return (Criteria) this;
        }

        public Criteria andActualContentIn(List<String> values) {
            addCriterion("actual_content in", values, "actualContent");
            return (Criteria) this;
        }

        public Criteria andActualContentNotIn(List<String> values) {
            addCriterion("actual_content not in", values, "actualContent");
            return (Criteria) this;
        }

        public Criteria andActualContentBetween(String value1, String value2) {
            addCriterion("actual_content between", value1, value2, "actualContent");
            return (Criteria) this;
        }

        public Criteria andActualContentNotBetween(String value1, String value2) {
            addCriterion("actual_content not between", value1, value2, "actualContent");
            return (Criteria) this;
        }

        public Criteria andActionOutlayIsNull() {
            addCriterion("action_outlay is null");
            return (Criteria) this;
        }

        public Criteria andActionOutlayIsNotNull() {
            addCriterion("action_outlay is not null");
            return (Criteria) this;
        }

        public Criteria andActionOutlayEqualTo(Double value) {
            addCriterion("action_outlay =", value, "actionOutlay");
            return (Criteria) this;
        }

        public Criteria andActionOutlayNotEqualTo(Double value) {
            addCriterion("action_outlay <>", value, "actionOutlay");
            return (Criteria) this;
        }

        public Criteria andActionOutlayGreaterThan(Double value) {
            addCriterion("action_outlay >", value, "actionOutlay");
            return (Criteria) this;
        }

        public Criteria andActionOutlayGreaterThanOrEqualTo(Double value) {
            addCriterion("action_outlay >=", value, "actionOutlay");
            return (Criteria) this;
        }

        public Criteria andActionOutlayLessThan(Double value) {
            addCriterion("action_outlay <", value, "actionOutlay");
            return (Criteria) this;
        }

        public Criteria andActionOutlayLessThanOrEqualTo(Double value) {
            addCriterion("action_outlay <=", value, "actionOutlay");
            return (Criteria) this;
        }

        public Criteria andActionOutlayIn(List<Double> values) {
            addCriterion("action_outlay in", values, "actionOutlay");
            return (Criteria) this;
        }

        public Criteria andActionOutlayNotIn(List<Double> values) {
            addCriterion("action_outlay not in", values, "actionOutlay");
            return (Criteria) this;
        }

        public Criteria andActionOutlayBetween(Double value1, Double value2) {
            addCriterion("action_outlay between", value1, value2, "actionOutlay");
            return (Criteria) this;
        }

        public Criteria andActionOutlayNotBetween(Double value1, Double value2) {
            addCriterion("action_outlay not between", value1, value2, "actionOutlay");
            return (Criteria) this;
        }

        public Criteria andActualOutlayIsNull() {
            addCriterion("actual_outlay is null");
            return (Criteria) this;
        }

        public Criteria andActualOutlayIsNotNull() {
            addCriterion("actual_outlay is not null");
            return (Criteria) this;
        }

        public Criteria andActualOutlayEqualTo(Double value) {
            addCriterion("actual_outlay =", value, "actualOutlay");
            return (Criteria) this;
        }

        public Criteria andActualOutlayNotEqualTo(Double value) {
            addCriterion("actual_outlay <>", value, "actualOutlay");
            return (Criteria) this;
        }

        public Criteria andActualOutlayGreaterThan(Double value) {
            addCriterion("actual_outlay >", value, "actualOutlay");
            return (Criteria) this;
        }

        public Criteria andActualOutlayGreaterThanOrEqualTo(Double value) {
            addCriterion("actual_outlay >=", value, "actualOutlay");
            return (Criteria) this;
        }

        public Criteria andActualOutlayLessThan(Double value) {
            addCriterion("actual_outlay <", value, "actualOutlay");
            return (Criteria) this;
        }

        public Criteria andActualOutlayLessThanOrEqualTo(Double value) {
            addCriterion("actual_outlay <=", value, "actualOutlay");
            return (Criteria) this;
        }

        public Criteria andActualOutlayIn(List<Double> values) {
            addCriterion("actual_outlay in", values, "actualOutlay");
            return (Criteria) this;
        }

        public Criteria andActualOutlayNotIn(List<Double> values) {
            addCriterion("actual_outlay not in", values, "actualOutlay");
            return (Criteria) this;
        }

        public Criteria andActualOutlayBetween(Double value1, Double value2) {
            addCriterion("actual_outlay between", value1, value2, "actualOutlay");
            return (Criteria) this;
        }

        public Criteria andActualOutlayNotBetween(Double value1, Double value2) {
            addCriterion("actual_outlay not between", value1, value2, "actualOutlay");
            return (Criteria) this;
        }

        public Criteria andExamineIdIsNull() {
            addCriterion("examine_id is null");
            return (Criteria) this;
        }

        public Criteria andExamineIdIsNotNull() {
            addCriterion("examine_id is not null");
            return (Criteria) this;
        }

        public Criteria andExamineIdEqualTo(Integer value) {
            addCriterion("examine_id =", value, "examineId");
            return (Criteria) this;
        }

        public Criteria andExamineIdNotEqualTo(Integer value) {
            addCriterion("examine_id <>", value, "examineId");
            return (Criteria) this;
        }

        public Criteria andExamineIdGreaterThan(Integer value) {
            addCriterion("examine_id >", value, "examineId");
            return (Criteria) this;
        }

        public Criteria andExamineIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("examine_id >=", value, "examineId");
            return (Criteria) this;
        }

        public Criteria andExamineIdLessThan(Integer value) {
            addCriterion("examine_id <", value, "examineId");
            return (Criteria) this;
        }

        public Criteria andExamineIdLessThanOrEqualTo(Integer value) {
            addCriterion("examine_id <=", value, "examineId");
            return (Criteria) this;
        }

        public Criteria andExamineIdIn(List<Integer> values) {
            addCriterion("examine_id in", values, "examineId");
            return (Criteria) this;
        }

        public Criteria andExamineIdNotIn(List<Integer> values) {
            addCriterion("examine_id not in", values, "examineId");
            return (Criteria) this;
        }

        public Criteria andExamineIdBetween(Integer value1, Integer value2) {
            addCriterion("examine_id between", value1, value2, "examineId");
            return (Criteria) this;
        }

        public Criteria andExamineIdNotBetween(Integer value1, Integer value2) {
            addCriterion("examine_id not between", value1, value2, "examineId");
            return (Criteria) this;
        }

        public Criteria andExamineNameIsNull() {
            addCriterion("examine_name is null");
            return (Criteria) this;
        }

        public Criteria andExamineNameIsNotNull() {
            addCriterion("examine_name is not null");
            return (Criteria) this;
        }

        public Criteria andExamineNameEqualTo(String value) {
            addCriterion("examine_name =", value, "examineName");
            return (Criteria) this;
        }

        public Criteria andExamineNameNotEqualTo(String value) {
            addCriterion("examine_name <>", value, "examineName");
            return (Criteria) this;
        }

        public Criteria andExamineNameGreaterThan(String value) {
            addCriterion("examine_name >", value, "examineName");
            return (Criteria) this;
        }

        public Criteria andExamineNameGreaterThanOrEqualTo(String value) {
            addCriterion("examine_name >=", value, "examineName");
            return (Criteria) this;
        }

        public Criteria andExamineNameLessThan(String value) {
            addCriterion("examine_name <", value, "examineName");
            return (Criteria) this;
        }

        public Criteria andExamineNameLessThanOrEqualTo(String value) {
            addCriterion("examine_name <=", value, "examineName");
            return (Criteria) this;
        }

        public Criteria andExamineNameLike(String value) {
            addCriterion("examine_name like", value, "examineName");
            return (Criteria) this;
        }

        public Criteria andExamineNameNotLike(String value) {
            addCriterion("examine_name not like", value, "examineName");
            return (Criteria) this;
        }

        public Criteria andExamineNameIn(List<String> values) {
            addCriterion("examine_name in", values, "examineName");
            return (Criteria) this;
        }

        public Criteria andExamineNameNotIn(List<String> values) {
            addCriterion("examine_name not in", values, "examineName");
            return (Criteria) this;
        }

        public Criteria andExamineNameBetween(String value1, String value2) {
            addCriterion("examine_name between", value1, value2, "examineName");
            return (Criteria) this;
        }

        public Criteria andExamineNameNotBetween(String value1, String value2) {
            addCriterion("examine_name not between", value1, value2, "examineName");
            return (Criteria) this;
        }

        public Criteria andExamineTimeIsNull() {
            addCriterion("examine_time is null");
            return (Criteria) this;
        }

        public Criteria andExamineTimeIsNotNull() {
            addCriterion("examine_time is not null");
            return (Criteria) this;
        }

        public Criteria andExamineTimeEqualTo(Date value) {
            addCriterion("examine_time =", value, "examineTime");
            return (Criteria) this;
        }

        public Criteria andExamineTimeNotEqualTo(Date value) {
            addCriterion("examine_time <>", value, "examineTime");
            return (Criteria) this;
        }

        public Criteria andExamineTimeGreaterThan(Date value) {
            addCriterion("examine_time >", value, "examineTime");
            return (Criteria) this;
        }

        public Criteria andExamineTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("examine_time >=", value, "examineTime");
            return (Criteria) this;
        }

        public Criteria andExamineTimeLessThan(Date value) {
            addCriterion("examine_time <", value, "examineTime");
            return (Criteria) this;
        }

        public Criteria andExamineTimeLessThanOrEqualTo(Date value) {
            addCriterion("examine_time <=", value, "examineTime");
            return (Criteria) this;
        }

        public Criteria andExamineTimeIn(List<Date> values) {
            addCriterion("examine_time in", values, "examineTime");
            return (Criteria) this;
        }

        public Criteria andExamineTimeNotIn(List<Date> values) {
            addCriterion("examine_time not in", values, "examineTime");
            return (Criteria) this;
        }

        public Criteria andExamineTimeBetween(Date value1, Date value2) {
            addCriterion("examine_time between", value1, value2, "examineTime");
            return (Criteria) this;
        }

        public Criteria andExamineTimeNotBetween(Date value1, Date value2) {
            addCriterion("examine_time not between", value1, value2, "examineTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andActionImagesIsNull() {
            addCriterion("action_images is null");
            return (Criteria) this;
        }

        public Criteria andActionImagesIsNotNull() {
            addCriterion("action_images is not null");
            return (Criteria) this;
        }

        public Criteria andActionImagesEqualTo(String value) {
            addCriterion("action_images =", value, "actionImages");
            return (Criteria) this;
        }

        public Criteria andActionImagesNotEqualTo(String value) {
            addCriterion("action_images <>", value, "actionImages");
            return (Criteria) this;
        }

        public Criteria andActionImagesGreaterThan(String value) {
            addCriterion("action_images >", value, "actionImages");
            return (Criteria) this;
        }

        public Criteria andActionImagesGreaterThanOrEqualTo(String value) {
            addCriterion("action_images >=", value, "actionImages");
            return (Criteria) this;
        }

        public Criteria andActionImagesLessThan(String value) {
            addCriterion("action_images <", value, "actionImages");
            return (Criteria) this;
        }

        public Criteria andActionImagesLessThanOrEqualTo(String value) {
            addCriterion("action_images <=", value, "actionImages");
            return (Criteria) this;
        }

        public Criteria andActionImagesLike(String value) {
            addCriterion("action_images like", value, "actionImages");
            return (Criteria) this;
        }

        public Criteria andActionImagesNotLike(String value) {
            addCriterion("action_images not like", value, "actionImages");
            return (Criteria) this;
        }

        public Criteria andActionImagesIn(List<String> values) {
            addCriterion("action_images in", values, "actionImages");
            return (Criteria) this;
        }

        public Criteria andActionImagesNotIn(List<String> values) {
            addCriterion("action_images not in", values, "actionImages");
            return (Criteria) this;
        }

        public Criteria andActionImagesBetween(String value1, String value2) {
            addCriterion("action_images between", value1, value2, "actionImages");
            return (Criteria) this;
        }

        public Criteria andActionImagesNotBetween(String value1, String value2) {
            addCriterion("action_images not between", value1, value2, "actionImages");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lovers_action_workflow
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 25 10:59:33 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lovers_action_workflow
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}