package com.lovers.java.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LoversSpaceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lovers_space
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lovers_space
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lovers_space
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_space
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public LoversSpaceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_space
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_space
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_space
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_space
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_space
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_space
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_space
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_space
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_space
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovers_space
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lovers_space
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSpaceIdIsNull() {
            addCriterion("space_id is null");
            return (Criteria) this;
        }

        public Criteria andSpaceIdIsNotNull() {
            addCriterion("space_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpaceIdEqualTo(Integer value) {
            addCriterion("space_id =", value, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceIdNotEqualTo(Integer value) {
            addCriterion("space_id <>", value, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceIdGreaterThan(Integer value) {
            addCriterion("space_id >", value, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("space_id >=", value, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceIdLessThan(Integer value) {
            addCriterion("space_id <", value, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceIdLessThanOrEqualTo(Integer value) {
            addCriterion("space_id <=", value, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceIdIn(List<Integer> values) {
            addCriterion("space_id in", values, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceIdNotIn(List<Integer> values) {
            addCriterion("space_id not in", values, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceIdBetween(Integer value1, Integer value2) {
            addCriterion("space_id between", value1, value2, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("space_id not between", value1, value2, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceNameIsNull() {
            addCriterion("space_name is null");
            return (Criteria) this;
        }

        public Criteria andSpaceNameIsNotNull() {
            addCriterion("space_name is not null");
            return (Criteria) this;
        }

        public Criteria andSpaceNameEqualTo(String value) {
            addCriterion("space_name =", value, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameNotEqualTo(String value) {
            addCriterion("space_name <>", value, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameGreaterThan(String value) {
            addCriterion("space_name >", value, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameGreaterThanOrEqualTo(String value) {
            addCriterion("space_name >=", value, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameLessThan(String value) {
            addCriterion("space_name <", value, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameLessThanOrEqualTo(String value) {
            addCriterion("space_name <=", value, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameLike(String value) {
            addCriterion("space_name like", value, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameNotLike(String value) {
            addCriterion("space_name not like", value, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameIn(List<String> values) {
            addCriterion("space_name in", values, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameNotIn(List<String> values) {
            addCriterion("space_name not in", values, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameBetween(String value1, String value2) {
            addCriterion("space_name between", value1, value2, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameNotBetween(String value1, String value2) {
            addCriterion("space_name not between", value1, value2, "spaceName");
            return (Criteria) this;
        }

        public Criteria andUserIdManIsNull() {
            addCriterion("user_id_man is null");
            return (Criteria) this;
        }

        public Criteria andUserIdManIsNotNull() {
            addCriterion("user_id_man is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdManEqualTo(Integer value) {
            addCriterion("user_id_man =", value, "userIdMan");
            return (Criteria) this;
        }

        public Criteria andUserIdManNotEqualTo(Integer value) {
            addCriterion("user_id_man <>", value, "userIdMan");
            return (Criteria) this;
        }

        public Criteria andUserIdManGreaterThan(Integer value) {
            addCriterion("user_id_man >", value, "userIdMan");
            return (Criteria) this;
        }

        public Criteria andUserIdManGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id_man >=", value, "userIdMan");
            return (Criteria) this;
        }

        public Criteria andUserIdManLessThan(Integer value) {
            addCriterion("user_id_man <", value, "userIdMan");
            return (Criteria) this;
        }

        public Criteria andUserIdManLessThanOrEqualTo(Integer value) {
            addCriterion("user_id_man <=", value, "userIdMan");
            return (Criteria) this;
        }

        public Criteria andUserIdManIn(List<Integer> values) {
            addCriterion("user_id_man in", values, "userIdMan");
            return (Criteria) this;
        }

        public Criteria andUserIdManNotIn(List<Integer> values) {
            addCriterion("user_id_man not in", values, "userIdMan");
            return (Criteria) this;
        }

        public Criteria andUserIdManBetween(Integer value1, Integer value2) {
            addCriterion("user_id_man between", value1, value2, "userIdMan");
            return (Criteria) this;
        }

        public Criteria andUserIdManNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id_man not between", value1, value2, "userIdMan");
            return (Criteria) this;
        }

        public Criteria andUserIdWomanIsNull() {
            addCriterion("user_id_woman is null");
            return (Criteria) this;
        }

        public Criteria andUserIdWomanIsNotNull() {
            addCriterion("user_id_woman is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdWomanEqualTo(Integer value) {
            addCriterion("user_id_woman =", value, "userIdWoman");
            return (Criteria) this;
        }

        public Criteria andUserIdWomanNotEqualTo(Integer value) {
            addCriterion("user_id_woman <>", value, "userIdWoman");
            return (Criteria) this;
        }

        public Criteria andUserIdWomanGreaterThan(Integer value) {
            addCriterion("user_id_woman >", value, "userIdWoman");
            return (Criteria) this;
        }

        public Criteria andUserIdWomanGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id_woman >=", value, "userIdWoman");
            return (Criteria) this;
        }

        public Criteria andUserIdWomanLessThan(Integer value) {
            addCriterion("user_id_woman <", value, "userIdWoman");
            return (Criteria) this;
        }

        public Criteria andUserIdWomanLessThanOrEqualTo(Integer value) {
            addCriterion("user_id_woman <=", value, "userIdWoman");
            return (Criteria) this;
        }

        public Criteria andUserIdWomanIn(List<Integer> values) {
            addCriterion("user_id_woman in", values, "userIdWoman");
            return (Criteria) this;
        }

        public Criteria andUserIdWomanNotIn(List<Integer> values) {
            addCriterion("user_id_woman not in", values, "userIdWoman");
            return (Criteria) this;
        }

        public Criteria andUserIdWomanBetween(Integer value1, Integer value2) {
            addCriterion("user_id_woman between", value1, value2, "userIdWoman");
            return (Criteria) this;
        }

        public Criteria andUserIdWomanNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id_woman not between", value1, value2, "userIdWoman");
            return (Criteria) this;
        }

        public Criteria andSpaceBackgroundIsNull() {
            addCriterion("space_background is null");
            return (Criteria) this;
        }

        public Criteria andSpaceBackgroundIsNotNull() {
            addCriterion("space_background is not null");
            return (Criteria) this;
        }

        public Criteria andSpaceBackgroundEqualTo(Integer value) {
            addCriterion("space_background =", value, "spaceBackground");
            return (Criteria) this;
        }

        public Criteria andSpaceBackgroundNotEqualTo(Integer value) {
            addCriterion("space_background <>", value, "spaceBackground");
            return (Criteria) this;
        }

        public Criteria andSpaceBackgroundGreaterThan(Integer value) {
            addCriterion("space_background >", value, "spaceBackground");
            return (Criteria) this;
        }

        public Criteria andSpaceBackgroundGreaterThanOrEqualTo(Integer value) {
            addCriterion("space_background >=", value, "spaceBackground");
            return (Criteria) this;
        }

        public Criteria andSpaceBackgroundLessThan(Integer value) {
            addCriterion("space_background <", value, "spaceBackground");
            return (Criteria) this;
        }

        public Criteria andSpaceBackgroundLessThanOrEqualTo(Integer value) {
            addCriterion("space_background <=", value, "spaceBackground");
            return (Criteria) this;
        }

        public Criteria andSpaceBackgroundIn(List<Integer> values) {
            addCriterion("space_background in", values, "spaceBackground");
            return (Criteria) this;
        }

        public Criteria andSpaceBackgroundNotIn(List<Integer> values) {
            addCriterion("space_background not in", values, "spaceBackground");
            return (Criteria) this;
        }

        public Criteria andSpaceBackgroundBetween(Integer value1, Integer value2) {
            addCriterion("space_background between", value1, value2, "spaceBackground");
            return (Criteria) this;
        }

        public Criteria andSpaceBackgroundNotBetween(Integer value1, Integer value2) {
            addCriterion("space_background not between", value1, value2, "spaceBackground");
            return (Criteria) this;
        }

        public Criteria andSpaceContentIsNull() {
            addCriterion("space_content is null");
            return (Criteria) this;
        }

        public Criteria andSpaceContentIsNotNull() {
            addCriterion("space_content is not null");
            return (Criteria) this;
        }

        public Criteria andSpaceContentEqualTo(String value) {
            addCriterion("space_content =", value, "spaceContent");
            return (Criteria) this;
        }

        public Criteria andSpaceContentNotEqualTo(String value) {
            addCriterion("space_content <>", value, "spaceContent");
            return (Criteria) this;
        }

        public Criteria andSpaceContentGreaterThan(String value) {
            addCriterion("space_content >", value, "spaceContent");
            return (Criteria) this;
        }

        public Criteria andSpaceContentGreaterThanOrEqualTo(String value) {
            addCriterion("space_content >=", value, "spaceContent");
            return (Criteria) this;
        }

        public Criteria andSpaceContentLessThan(String value) {
            addCriterion("space_content <", value, "spaceContent");
            return (Criteria) this;
        }

        public Criteria andSpaceContentLessThanOrEqualTo(String value) {
            addCriterion("space_content <=", value, "spaceContent");
            return (Criteria) this;
        }

        public Criteria andSpaceContentLike(String value) {
            addCriterion("space_content like", value, "spaceContent");
            return (Criteria) this;
        }

        public Criteria andSpaceContentNotLike(String value) {
            addCriterion("space_content not like", value, "spaceContent");
            return (Criteria) this;
        }

        public Criteria andSpaceContentIn(List<String> values) {
            addCriterion("space_content in", values, "spaceContent");
            return (Criteria) this;
        }

        public Criteria andSpaceContentNotIn(List<String> values) {
            addCriterion("space_content not in", values, "spaceContent");
            return (Criteria) this;
        }

        public Criteria andSpaceContentBetween(String value1, String value2) {
            addCriterion("space_content between", value1, value2, "spaceContent");
            return (Criteria) this;
        }

        public Criteria andSpaceContentNotBetween(String value1, String value2) {
            addCriterion("space_content not between", value1, value2, "spaceContent");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lovers_space
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 25 10:59:33 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lovers_space
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}