package com.lovers.java.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserMoodRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_mood_record
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_mood_record
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_mood_record
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_record
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public UserMoodRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_record
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_record
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_record
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_record
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_record
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_record
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_record
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_record
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_record
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mood_record
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_mood_record
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRecordIdIsNull() {
            addCriterion("record_id is null");
            return (Criteria) this;
        }

        public Criteria andRecordIdIsNotNull() {
            addCriterion("record_id is not null");
            return (Criteria) this;
        }

        public Criteria andRecordIdEqualTo(Integer value) {
            addCriterion("record_id =", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotEqualTo(Integer value) {
            addCriterion("record_id <>", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdGreaterThan(Integer value) {
            addCriterion("record_id >", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("record_id >=", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLessThan(Integer value) {
            addCriterion("record_id <", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLessThanOrEqualTo(Integer value) {
            addCriterion("record_id <=", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdIn(List<Integer> values) {
            addCriterion("record_id in", values, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotIn(List<Integer> values) {
            addCriterion("record_id not in", values, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdBetween(Integer value1, Integer value2) {
            addCriterion("record_id between", value1, value2, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotBetween(Integer value1, Integer value2) {
            addCriterion("record_id not between", value1, value2, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordTitleIsNull() {
            addCriterion("record_title is null");
            return (Criteria) this;
        }

        public Criteria andRecordTitleIsNotNull() {
            addCriterion("record_title is not null");
            return (Criteria) this;
        }

        public Criteria andRecordTitleEqualTo(String value) {
            addCriterion("record_title =", value, "recordTitle");
            return (Criteria) this;
        }

        public Criteria andRecordTitleNotEqualTo(String value) {
            addCriterion("record_title <>", value, "recordTitle");
            return (Criteria) this;
        }

        public Criteria andRecordTitleGreaterThan(String value) {
            addCriterion("record_title >", value, "recordTitle");
            return (Criteria) this;
        }

        public Criteria andRecordTitleGreaterThanOrEqualTo(String value) {
            addCriterion("record_title >=", value, "recordTitle");
            return (Criteria) this;
        }

        public Criteria andRecordTitleLessThan(String value) {
            addCriterion("record_title <", value, "recordTitle");
            return (Criteria) this;
        }

        public Criteria andRecordTitleLessThanOrEqualTo(String value) {
            addCriterion("record_title <=", value, "recordTitle");
            return (Criteria) this;
        }

        public Criteria andRecordTitleLike(String value) {
            addCriterion("record_title like", value, "recordTitle");
            return (Criteria) this;
        }

        public Criteria andRecordTitleNotLike(String value) {
            addCriterion("record_title not like", value, "recordTitle");
            return (Criteria) this;
        }

        public Criteria andRecordTitleIn(List<String> values) {
            addCriterion("record_title in", values, "recordTitle");
            return (Criteria) this;
        }

        public Criteria andRecordTitleNotIn(List<String> values) {
            addCriterion("record_title not in", values, "recordTitle");
            return (Criteria) this;
        }

        public Criteria andRecordTitleBetween(String value1, String value2) {
            addCriterion("record_title between", value1, value2, "recordTitle");
            return (Criteria) this;
        }

        public Criteria andRecordTitleNotBetween(String value1, String value2) {
            addCriterion("record_title not between", value1, value2, "recordTitle");
            return (Criteria) this;
        }

        public Criteria andRecordImagesIsNull() {
            addCriterion("record_images is null");
            return (Criteria) this;
        }

        public Criteria andRecordImagesIsNotNull() {
            addCriterion("record_images is not null");
            return (Criteria) this;
        }

        public Criteria andRecordImagesEqualTo(String value) {
            addCriterion("record_images =", value, "recordImages");
            return (Criteria) this;
        }

        public Criteria andRecordImagesNotEqualTo(String value) {
            addCriterion("record_images <>", value, "recordImages");
            return (Criteria) this;
        }

        public Criteria andRecordImagesGreaterThan(String value) {
            addCriterion("record_images >", value, "recordImages");
            return (Criteria) this;
        }

        public Criteria andRecordImagesGreaterThanOrEqualTo(String value) {
            addCriterion("record_images >=", value, "recordImages");
            return (Criteria) this;
        }

        public Criteria andRecordImagesLessThan(String value) {
            addCriterion("record_images <", value, "recordImages");
            return (Criteria) this;
        }

        public Criteria andRecordImagesLessThanOrEqualTo(String value) {
            addCriterion("record_images <=", value, "recordImages");
            return (Criteria) this;
        }

        public Criteria andRecordImagesLike(String value) {
            addCriterion("record_images like", value, "recordImages");
            return (Criteria) this;
        }

        public Criteria andRecordImagesNotLike(String value) {
            addCriterion("record_images not like", value, "recordImages");
            return (Criteria) this;
        }

        public Criteria andRecordImagesIn(List<String> values) {
            addCriterion("record_images in", values, "recordImages");
            return (Criteria) this;
        }

        public Criteria andRecordImagesNotIn(List<String> values) {
            addCriterion("record_images not in", values, "recordImages");
            return (Criteria) this;
        }

        public Criteria andRecordImagesBetween(String value1, String value2) {
            addCriterion("record_images between", value1, value2, "recordImages");
            return (Criteria) this;
        }

        public Criteria andRecordImagesNotBetween(String value1, String value2) {
            addCriterion("record_images not between", value1, value2, "recordImages");
            return (Criteria) this;
        }

        public Criteria andRecordContentIsNull() {
            addCriterion("record_content is null");
            return (Criteria) this;
        }

        public Criteria andRecordContentIsNotNull() {
            addCriterion("record_content is not null");
            return (Criteria) this;
        }

        public Criteria andRecordContentEqualTo(String value) {
            addCriterion("record_content =", value, "recordContent");
            return (Criteria) this;
        }

        public Criteria andRecordContentNotEqualTo(String value) {
            addCriterion("record_content <>", value, "recordContent");
            return (Criteria) this;
        }

        public Criteria andRecordContentGreaterThan(String value) {
            addCriterion("record_content >", value, "recordContent");
            return (Criteria) this;
        }

        public Criteria andRecordContentGreaterThanOrEqualTo(String value) {
            addCriterion("record_content >=", value, "recordContent");
            return (Criteria) this;
        }

        public Criteria andRecordContentLessThan(String value) {
            addCriterion("record_content <", value, "recordContent");
            return (Criteria) this;
        }

        public Criteria andRecordContentLessThanOrEqualTo(String value) {
            addCriterion("record_content <=", value, "recordContent");
            return (Criteria) this;
        }

        public Criteria andRecordContentLike(String value) {
            addCriterion("record_content like", value, "recordContent");
            return (Criteria) this;
        }

        public Criteria andRecordContentNotLike(String value) {
            addCriterion("record_content not like", value, "recordContent");
            return (Criteria) this;
        }

        public Criteria andRecordContentIn(List<String> values) {
            addCriterion("record_content in", values, "recordContent");
            return (Criteria) this;
        }

        public Criteria andRecordContentNotIn(List<String> values) {
            addCriterion("record_content not in", values, "recordContent");
            return (Criteria) this;
        }

        public Criteria andRecordContentBetween(String value1, String value2) {
            addCriterion("record_content between", value1, value2, "recordContent");
            return (Criteria) this;
        }

        public Criteria andRecordContentNotBetween(String value1, String value2) {
            addCriterion("record_content not between", value1, value2, "recordContent");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andIsHiddenIsNull() {
            addCriterion("is_hidden is null");
            return (Criteria) this;
        }

        public Criteria andIsHiddenIsNotNull() {
            addCriterion("is_hidden is not null");
            return (Criteria) this;
        }

        public Criteria andIsHiddenEqualTo(Integer value) {
            addCriterion("is_hidden =", value, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenNotEqualTo(Integer value) {
            addCriterion("is_hidden <>", value, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenGreaterThan(Integer value) {
            addCriterion("is_hidden >", value, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_hidden >=", value, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenLessThan(Integer value) {
            addCriterion("is_hidden <", value, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenLessThanOrEqualTo(Integer value) {
            addCriterion("is_hidden <=", value, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenIn(List<Integer> values) {
            addCriterion("is_hidden in", values, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenNotIn(List<Integer> values) {
            addCriterion("is_hidden not in", values, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenBetween(Integer value1, Integer value2) {
            addCriterion("is_hidden between", value1, value2, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenNotBetween(Integer value1, Integer value2) {
            addCriterion("is_hidden not between", value1, value2, "isHidden");
            return (Criteria) this;
        }

        public Criteria andVisitorNumberIsNull() {
            addCriterion("visitor_number is null");
            return (Criteria) this;
        }

        public Criteria andVisitorNumberIsNotNull() {
            addCriterion("visitor_number is not null");
            return (Criteria) this;
        }

        public Criteria andVisitorNumberEqualTo(Integer value) {
            addCriterion("visitor_number =", value, "visitorNumber");
            return (Criteria) this;
        }

        public Criteria andVisitorNumberNotEqualTo(Integer value) {
            addCriterion("visitor_number <>", value, "visitorNumber");
            return (Criteria) this;
        }

        public Criteria andVisitorNumberGreaterThan(Integer value) {
            addCriterion("visitor_number >", value, "visitorNumber");
            return (Criteria) this;
        }

        public Criteria andVisitorNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("visitor_number >=", value, "visitorNumber");
            return (Criteria) this;
        }

        public Criteria andVisitorNumberLessThan(Integer value) {
            addCriterion("visitor_number <", value, "visitorNumber");
            return (Criteria) this;
        }

        public Criteria andVisitorNumberLessThanOrEqualTo(Integer value) {
            addCriterion("visitor_number <=", value, "visitorNumber");
            return (Criteria) this;
        }

        public Criteria andVisitorNumberIn(List<Integer> values) {
            addCriterion("visitor_number in", values, "visitorNumber");
            return (Criteria) this;
        }

        public Criteria andVisitorNumberNotIn(List<Integer> values) {
            addCriterion("visitor_number not in", values, "visitorNumber");
            return (Criteria) this;
        }

        public Criteria andVisitorNumberBetween(Integer value1, Integer value2) {
            addCriterion("visitor_number between", value1, value2, "visitorNumber");
            return (Criteria) this;
        }

        public Criteria andVisitorNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("visitor_number not between", value1, value2, "visitorNumber");
            return (Criteria) this;
        }

        public Criteria andCommentNumberIsNull() {
            addCriterion("comment_number is null");
            return (Criteria) this;
        }

        public Criteria andCommentNumberIsNotNull() {
            addCriterion("comment_number is not null");
            return (Criteria) this;
        }

        public Criteria andCommentNumberEqualTo(Integer value) {
            addCriterion("comment_number =", value, "commentNumber");
            return (Criteria) this;
        }

        public Criteria andCommentNumberNotEqualTo(Integer value) {
            addCriterion("comment_number <>", value, "commentNumber");
            return (Criteria) this;
        }

        public Criteria andCommentNumberGreaterThan(Integer value) {
            addCriterion("comment_number >", value, "commentNumber");
            return (Criteria) this;
        }

        public Criteria andCommentNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("comment_number >=", value, "commentNumber");
            return (Criteria) this;
        }

        public Criteria andCommentNumberLessThan(Integer value) {
            addCriterion("comment_number <", value, "commentNumber");
            return (Criteria) this;
        }

        public Criteria andCommentNumberLessThanOrEqualTo(Integer value) {
            addCriterion("comment_number <=", value, "commentNumber");
            return (Criteria) this;
        }

        public Criteria andCommentNumberIn(List<Integer> values) {
            addCriterion("comment_number in", values, "commentNumber");
            return (Criteria) this;
        }

        public Criteria andCommentNumberNotIn(List<Integer> values) {
            addCriterion("comment_number not in", values, "commentNumber");
            return (Criteria) this;
        }

        public Criteria andCommentNumberBetween(Integer value1, Integer value2) {
            addCriterion("comment_number between", value1, value2, "commentNumber");
            return (Criteria) this;
        }

        public Criteria andCommentNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("comment_number not between", value1, value2, "commentNumber");
            return (Criteria) this;
        }

        public Criteria andApproverNumberIsNull() {
            addCriterion("approver_number is null");
            return (Criteria) this;
        }

        public Criteria andApproverNumberIsNotNull() {
            addCriterion("approver_number is not null");
            return (Criteria) this;
        }

        public Criteria andApproverNumberEqualTo(Integer value) {
            addCriterion("approver_number =", value, "approverNumber");
            return (Criteria) this;
        }

        public Criteria andApproverNumberNotEqualTo(Integer value) {
            addCriterion("approver_number <>", value, "approverNumber");
            return (Criteria) this;
        }

        public Criteria andApproverNumberGreaterThan(Integer value) {
            addCriterion("approver_number >", value, "approverNumber");
            return (Criteria) this;
        }

        public Criteria andApproverNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("approver_number >=", value, "approverNumber");
            return (Criteria) this;
        }

        public Criteria andApproverNumberLessThan(Integer value) {
            addCriterion("approver_number <", value, "approverNumber");
            return (Criteria) this;
        }

        public Criteria andApproverNumberLessThanOrEqualTo(Integer value) {
            addCriterion("approver_number <=", value, "approverNumber");
            return (Criteria) this;
        }

        public Criteria andApproverNumberIn(List<Integer> values) {
            addCriterion("approver_number in", values, "approverNumber");
            return (Criteria) this;
        }

        public Criteria andApproverNumberNotIn(List<Integer> values) {
            addCriterion("approver_number not in", values, "approverNumber");
            return (Criteria) this;
        }

        public Criteria andApproverNumberBetween(Integer value1, Integer value2) {
            addCriterion("approver_number between", value1, value2, "approverNumber");
            return (Criteria) this;
        }

        public Criteria andApproverNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("approver_number not between", value1, value2, "approverNumber");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_mood_record
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 25 10:59:33 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_mood_record
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}